services:
  challenge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-http.ayanides.cloud:80
      - OTEL_SERVICE_NAME=fastapi-observability-example
      - ENABLE_TRACING=true
      - ENABLE_METRICS=true
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
