services:
  challenge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENABLE_METRICS=false
      - ENABLE_TRACING=false
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otlp-http.ayanides.cloud:80
      - OTEL_SERVICE_NAME=fastapi-observability-example
      - ENABLE_PROFILING=true
      - PYROSCOPE_ENDPOINT=https://pyroscope.ayanides.cloud
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
