
version: "3.4"

services:
  app-a:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "app-a"

  app-b:
    build: .
    ports:
      - "8001:8000"
    environment:
      APP_NAME: "app-b"

  app-c:
    build: .
    ports:
      - "8002:8000"
    environment:
      APP_NAME: "app-c"
