version: '3.9'
services:
  us-east:
    environment:
      - REGION=us-east
    build:
      context: .

  eu-north:
    environment:
      - REGION=eu-north
    build:
      context: .

  ap-south:
    environment:
      - REGION=ap-south
    build:
      context: .
